"""extract_layout — read a .kicad_pcb and emit a layout.py-compatible Python dict.

Use this after editing positions in KiCad GUI to round-trip back to your
design's layout.py. Currently extracts positions only; tracks/vias/zones
remain in your original layout.py and are not modified.
"""
from __future__ import annotations
from pathlib import Path
from typing import Dict, Tuple
import pcbnew


def extract_positions(pcb_path: str | Path,
                      round_to_mm: float = 0.01) -> Dict[str, Tuple[float, float, float]]:
    """Read a .kicad_pcb and return a {ref: (x_mm, y_mm, rotation_deg)} dict.

    Args:
        pcb_path: path to .kicad_pcb file
        round_to_mm: round positions to this resolution (default 0.01mm)

    Returns dict keyed by reference designator.
    """
    board = pcbnew.LoadBoard(str(pcb_path))
    positions: Dict[str, Tuple[float, float, float]] = {}

    for fp in board.GetFootprints():
        ref = fp.GetReference()
        pos = fp.GetPosition()
        x = pcbnew.ToMM(pos.x)
        y = pcbnew.ToMM(pos.y)
        rot = fp.GetOrientationDegrees() % 360
        # Round
        x = round(x / round_to_mm) * round_to_mm
        y = round(y / round_to_mm) * round_to_mm
        rot = round(rot)
        positions[ref] = (x, y, float(rot))

    return positions


def write_layout_py(positions: Dict[str, Tuple[float, float, float]],
                    output_path: str | Path,
                    preserve_existing_routing: bool = True) -> None:
    """Write positions to a layout.py file.

    If preserve_existing_routing=True and the file exists, only the `positions`
    dict is replaced — `tracks`, `vias`, `zones`, etc. are preserved verbatim.
    """
    output_path = Path(output_path)

    new_positions_block = ["# === auto-generated by circuit_toolkit.builders.extract_layout ==="]
    new_positions_block.append("positions = {")
    # Sort: J first, U next, then alphabetical
    def _sort_key(ref):
        prefix = ref.rstrip("0123456789")
        order = {"J": 0, "U": 1, "Q": 2, "D": 3, "L": 4, "R": 5, "C": 6, "TP": 7, "H": 9}
        return (order.get(prefix, 8), ref)
    for ref in sorted(positions.keys(), key=_sort_key):
        x, y, rot = positions[ref]
        rot_str = f", {rot:g}" if rot else ""
        new_positions_block.append(f'    "{ref}": ({x:g}, {y:g}, {rot:g}),')
    new_positions_block.append("}")
    new_positions_block.append("# === end auto-generated ===")
    new_block = "\n".join(new_positions_block)

    if preserve_existing_routing and output_path.exists():
        existing = output_path.read_text()
        # Find the auto-generated block and replace just that
        start = existing.find("# === auto-generated")
        end = existing.find("# === end auto-generated ===")
        if start >= 0 and end >= 0:
            end_full = end + len("# === end auto-generated ===")
            new_content = existing[:start] + new_block + existing[end_full:]
        else:
            # No marker: prepend block
            new_content = new_block + "\n\n" + existing
    else:
        new_content = new_block + "\n"

    output_path.write_text(new_content)


def main():
    """CLI entry point: extract_layout <pcb_file> [layout.py]"""
    import sys
    if len(sys.argv) < 2:
        print("Usage: extract_layout <project.kicad_pcb> [layout.py]")
        sys.exit(2)
    pcb = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else "layout.py"
    positions = extract_positions(pcb)
    write_layout_py(positions, out)
    print(f"Wrote {len(positions)} positions to {out}")


if __name__ == "__main__":
    main()
