"""extract_layout — read a .kicad_pcb and emit a layout.py-compatible Python file.

Use this after editing positions / routes in KiCad GUI to round-trip back to
your design's layout.py. Captures positions, tracks, vias, and zones — every
element ``build_pcb()`` consumes — so the GUI edit and the text source stay
in sync. Anything not in those four lists (e.g. ``ref_text_overrides``,
``pad_zone_full``, ``outline``) is preserved verbatim by the marker-block
overwrite, since those tend to be hand-curated and are not extractable
unambiguously from a flat .kicad_pcb.
"""
from __future__ import annotations
from pathlib import Path
from typing import Dict, List, Tuple

import pcbnew


# Marker pairs the writer uses to delimit each auto-generated block.
_BLOCKS = [
    ("positions", "# === auto-generated positions ===",  "# === end positions ==="),
    ("tracks",    "# === auto-generated tracks ===",     "# === end tracks ==="),
    ("vias",      "# === auto-generated vias ===",       "# === end vias ==="),
    ("zones",     "# === auto-generated zones ===",      "# === end zones ==="),
]
# Legacy marker the original writer used (positions only) — recognised so
# upgrades are seamless: we replace the old single block with the new
# four-block layout on the next extract.
_LEGACY_MARKERS = ("# === auto-generated by circuit_toolkit.builders.extract_layout ===",
                   "# === end auto-generated ===")

_PAD_CONNECTION = {
    pcbnew.ZONE_CONNECTION_FULL:         "full",
    pcbnew.ZONE_CONNECTION_THERMAL:      "thermal",
    pcbnew.ZONE_CONNECTION_NONE:         "none",
    pcbnew.ZONE_CONNECTION_THT_THERMAL:  "thermal_through_holes",
    pcbnew.ZONE_CONNECTION_INHERITED:    "inherited",
}


# ── Extractors ────────────────────────────────────────────────────────────────

def extract_positions(pcb_path: str | Path,
                      round_to_mm: float = 0.01) -> Dict[str, Tuple[float, float, float]]:
    """Read a .kicad_pcb and return ``{ref: (x_mm, y_mm, rotation_deg)}``."""
    board = pcbnew.LoadBoard(str(pcb_path))
    positions: Dict[str, Tuple[float, float, float]] = {}
    for fp in board.GetFootprints():
        ref = fp.GetReference()
        pos = fp.GetPosition()
        x = round(pcbnew.ToMM(pos.x) / round_to_mm) * round_to_mm
        y = round(pcbnew.ToMM(pos.y) / round_to_mm) * round_to_mm
        rot = round(fp.GetOrientationDegrees() % 360)
        positions[ref] = (x, y, float(rot))
    return positions


def extract_tracks(pcb_path: str | Path,
                   round_to_mm: float = 0.001
                   ) -> List[Tuple[str, float, float, float, float, float, str]]:
    """Read a .kicad_pcb and return the track segments as
    ``[(net, x1, y1, x2, y2, width_mm, layer), ...]`` — the same shape
    ``build_pcb(tracks=...)`` accepts."""
    board = pcbnew.LoadBoard(str(pcb_path))
    out = []
    for t in board.GetTracks():
        if isinstance(t, pcbnew.PCB_VIA):
            continue
        s, e = t.GetStart(), t.GetEnd()
        out.append((
            t.GetNet().GetNetname(),
            round(pcbnew.ToMM(s.x) / round_to_mm) * round_to_mm,
            round(pcbnew.ToMM(s.y) / round_to_mm) * round_to_mm,
            round(pcbnew.ToMM(e.x) / round_to_mm) * round_to_mm,
            round(pcbnew.ToMM(e.y) / round_to_mm) * round_to_mm,
            round(pcbnew.ToMM(t.GetWidth()) / round_to_mm) * round_to_mm,
            t.GetLayerName(),
        ))
    return out


def extract_vias(pcb_path: str | Path,
                 round_to_mm: float = 0.001
                 ) -> List[Tuple[str, float, float, float, float]]:
    """Read a .kicad_pcb and return vias as ``[(net, x, y, drill_mm, size_mm), ...]``."""
    board = pcbnew.LoadBoard(str(pcb_path))
    out = []
    for t in board.GetTracks():
        if not isinstance(t, pcbnew.PCB_VIA):
            continue
        p = t.GetPosition()
        # PCB_VIA in KiCad 10 needs a layer arg for GetWidth(); F_Cu is the canonical pad.
        size = pcbnew.ToMM(t.GetWidth(pcbnew.F_Cu))
        out.append((
            t.GetNet().GetNetname(),
            round(pcbnew.ToMM(p.x) / round_to_mm) * round_to_mm,
            round(pcbnew.ToMM(p.y) / round_to_mm) * round_to_mm,
            round(pcbnew.ToMM(t.GetDrill()) / round_to_mm) * round_to_mm,
            round(size / round_to_mm) * round_to_mm,
        ))
    return out


def extract_zones(pcb_path: str | Path,
                  round_to_mm: float = 0.01) -> List[dict]:
    """Read a .kicad_pcb and return zones as a list of dicts shaped for
    ``build_pcb(zones=...)``: ``{"net", "layer", "polygon", "min_thickness",
    "pad_connection"}``. Multi-outline zones are emitted as one dict per outline."""
    board = pcbnew.LoadBoard(str(pcb_path))
    out = []
    for z in board.Zones():
        net = z.GetNet().GetNetname()
        layer = z.GetLayerName()
        thickness = pcbnew.ToMM(z.GetMinThickness())
        pad_conn = _PAD_CONNECTION.get(z.GetPadConnection(), "thermal")
        outlines = z.Outline()
        for i in range(outlines.OutlineCount()):
            ol = outlines.Outline(i)
            poly = []
            for k in range(ol.PointCount()):
                p = ol.CPoint(k)
                poly.append((
                    round(pcbnew.ToMM(p.x) / round_to_mm) * round_to_mm,
                    round(pcbnew.ToMM(p.y) / round_to_mm) * round_to_mm,
                ))
            out.append({
                "net": net,
                "layer": layer,
                "polygon": poly,
                "min_thickness": round(thickness / round_to_mm) * round_to_mm,
                "pad_connection": pad_conn,
            })
    return out


def extract_all(pcb_path: str | Path) -> dict:
    """Convenience: positions + tracks + vias + zones in one dict."""
    return {
        "positions": extract_positions(pcb_path),
        "tracks":    extract_tracks(pcb_path),
        "vias":      extract_vias(pcb_path),
        "zones":     extract_zones(pcb_path),
    }


# ── Writer ────────────────────────────────────────────────────────────────────

def _format_positions(positions) -> str:
    def _sort_key(ref):
        prefix = ref.rstrip("0123456789")
        order = {"J": 0, "U": 1, "Q": 2, "D": 3, "L": 4, "R": 5, "C": 6, "TP": 7, "H": 9}
        return (order.get(prefix, 8), ref)
    lines = ["positions = {"]
    for ref in sorted(positions.keys(), key=_sort_key):
        x, y, rot = positions[ref]
        lines.append(f'    "{ref}": ({x:g}, {y:g}, {rot:g}),')
    lines.append("}")
    return "\n".join(lines)


def _format_tracks(tracks) -> str:
    if not tracks:
        return "tracks = []"
    lines = ["tracks = ["]
    for net, x1, y1, x2, y2, w, layer in tracks:
        lines.append(f'    ({net!r}, {x1:g}, {y1:g}, {x2:g}, {y2:g}, {w:g}, {layer!r}),')
    lines.append("]")
    return "\n".join(lines)


def _format_vias(vias) -> str:
    if not vias:
        return "vias = []"
    lines = ["vias = ["]
    for net, x, y, drill, size in vias:
        lines.append(f'    ({net!r}, {x:g}, {y:g}, {drill:g}, {size:g}),')
    lines.append("]")
    return "\n".join(lines)


def _format_zones(zones) -> str:
    if not zones:
        return "zones = []"
    lines = ["zones = ["]
    for z in zones:
        lines.append("    {")
        lines.append(f'        "net": {z["net"]!r},')
        lines.append(f'        "layer": {z["layer"]!r},')
        poly = ", ".join(f"({x:g}, {y:g})" for x, y in z["polygon"])
        lines.append(f'        "polygon": [{poly}],')
        lines.append(f'        "min_thickness": {z["min_thickness"]:g},')
        lines.append(f'        "pad_connection": {z["pad_connection"]!r},')
        lines.append("    },")
    lines.append("]")
    return "\n".join(lines)


_FORMATTERS = {
    "positions": _format_positions,
    "tracks":    _format_tracks,
    "vias":      _format_vias,
    "zones":     _format_zones,
}


def _replace_or_append_block(text: str, start_marker: str, end_marker: str,
                             body: str) -> str:
    """Replace the body between matching markers; append the block if not found."""
    block = f"{start_marker}\n{body}\n{end_marker}"
    s = text.find(start_marker)
    if s < 0:
        sep = "\n\n" if text and not text.endswith("\n\n") else ""
        return text + sep + block + "\n"
    e = text.find(end_marker, s)
    if e < 0:
        return text + "\n" + block + "\n"
    return text[:s] + block + text[e + len(end_marker):]


def _strip_legacy_marker(text: str) -> str:
    """Drop the original single-block marker pair (positions only) so it
    doesn't leave a stale ``positions`` definition above the new four-block
    layout. The block contents are dropped along with the markers."""
    s = text.find(_LEGACY_MARKERS[0])
    if s < 0:
        return text
    e = text.find(_LEGACY_MARKERS[1], s)
    if e < 0:
        return text
    return text[:s] + text[e + len(_LEGACY_MARKERS[1]):]


def write_layout_py(positions=None,
                    tracks=None,
                    vias=None,
                    zones=None,
                    output_path: str | Path = "layout.py") -> None:
    """Write extracted layout artefacts back into ``layout.py``.

    Each kwarg that is ``None`` leaves its block alone (existing or absent).
    Other args are formatted into their auto-generated marker blocks; the rest
    of the file (docstrings, hand-edited overrides, ``outline``,
    ``ref_text_overrides``, ``pad_zone_full``, comments) is preserved verbatim.
    The first run on a file that contains the legacy single-block marker
    upgrades it to the new four-block layout."""
    output_path = Path(output_path)
    text = output_path.read_text() if output_path.exists() else ""
    text = _strip_legacy_marker(text)

    payload = {"positions": positions, "tracks": tracks,
               "vias": vias, "zones": zones}

    for name, start, end in _BLOCKS:
        data = payload[name]
        if data is None:
            continue
        body = _FORMATTERS[name](data)
        text = _replace_or_append_block(text, start, end, body)

    output_path.write_text(text)


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    """CLI: extract_layout <pcb_file> [layout.py] [--positions-only]"""
    import sys
    args = list(sys.argv[1:])
    positions_only = False
    if "--positions-only" in args:
        positions_only = True
        args.remove("--positions-only")
    if not args:
        print("Usage: extract_layout <project.kicad_pcb> [layout.py] [--positions-only]")
        sys.exit(2)
    pcb = args[0]
    out = args[1] if len(args) > 1 else "layout.py"

    if positions_only:
        write_layout_py(positions=extract_positions(pcb), output_path=out)
        print(f"Wrote positions to {out}")
    else:
        data = extract_all(pcb)
        write_layout_py(**data, output_path=out)
        print(f"Wrote {len(data['positions'])} positions, {len(data['tracks'])} tracks, "
              f"{len(data['vias'])} vias, {len(data['zones'])} zones to {out}")


if __name__ == "__main__":
    main()
